export type RankedEntry = {
  rank: number
  name: string
  year: string
  title: string
  avatar: string
  change: number
  tags?: string[]
  score: number
}

export const rankedEntries: RankedEntry[] = [
  {
    rank: 1,
    name: "True Adam",
    year: "'27",
    title: "Adam Walsh",
    avatar: "https://i.pravatar.cc/150?img=11",
    change: 0,
    tags: ["Current Protagonist"],
    score: 97,
  },
  {
    rank: 2,
    name: "Marcus Chen",
    year: "'28",
    title: "The Dark Knight",
    avatar: "https://i.pravatar.cc/150?img=12",
    change: 2,
    tags: [],
    score: 94,
  },
  {
    rank: 3,
    name: "Theo Martin",
    year: "'26",
    title: "Humble Mogger",
    avatar: "https://i.pravatar.cc/150?img=13",
    change: -1,
    score: 92,
  },
  {
    rank: 4,
    name: "Julian Park",
    year: "'29",
    title: "The Silent Storm",
    avatar: "https://i.pravatar.cc/150?img=14",
    change: 3,
    tags: ["Rising Fast"],
    score: 89,
  },
  {
    rank: 5,
    name: "Seb Nguyen",
    year: "'27",
    title: "Golden Ratio King",
    avatar: "https://i.pravatar.cc/150?img=15",
    change: -2,
    score: 87,
  },
  {
    rank: 6,
    name: "Dylan Torres",
    year: "'28",
    title: "The Enigma",
    avatar: "https://i.pravatar.cc/150?img=53",
    change: 0,
    score: 85,
  },
  {
    rank: 7,
    name: "Rafa Kim",
    year: "'26",
    title: "Sun-Kissed Prodigy",
    avatar: "https://i.pravatar.cc/150?img=51",
    change: 1,
    score: 83,
  },
  {
    rank: 8,
    name: "Nick Petrov",
    year: "'29",
    title: "Ice Cold Symmetry",
    avatar: "https://i.pravatar.cc/150?img=52",
    change: -3,
    score: 81,
  },
  {
    rank: 9,
    name: "Luke Brooks",
    year: "'27",
    title: "The Phantom",
    avatar: "https://i.pravatar.cc/150?img=33",
    change: 2,
    score: 79,
  },
  {
    rank: 10,
    name: "Henry Strand",
    year: "'28",
    title: "Nordic Thunder",
    avatar: "https://i.pravatar.cc/150?img=55",
    change: -1,
    score: 77,
  },
]

export const battleRoster: RankedEntry[] = [
  ...rankedEntries,
  {
    rank: 11,
    name: "Cash Reed",
    year: "'29",
    title: "The Underdog",
    avatar: "https://i.pravatar.cc/150?img=56",
    change: 4,
    score: 75,
  },
  {
    rank: 12,
    name: "Owen Blake",
    year: "'26",
    title: "Midnight Contender",
    avatar: "https://i.pravatar.cc/150?img=57",
    change: 0,
    score: 73,
  },
  {
    rank: 13,
    name: "Ezra Montague",
    year: "'28",
    title: "The Architect",
    avatar: "https://i.pravatar.cc/150?img=58",
    change: -2,
    score: 71,
  },
  {
    rank: 14,
    name: "Felix Harris",
    year: "'27",
    title: "Chrome Jaw",
    avatar: "https://i.pravatar.cc/150?img=59",
    change: 1,
    score: 69,
  },
  {
    rank: 15,
    name: "Grant Winter",
    year: "'29",
    title: "The Newcomer",
    avatar: "https://i.pravatar.cc/150?img=60",
    change: 5,
    score: 67,
  },
  {
    rank: 16,
    name: "Danny Hale",
    year: "'26",
    title: "Velvet Menace",
    avatar: "https://i.pravatar.cc/150?img=61",
    change: -1,
    score: 65,
  },
  {
    rank: 17,
    name: "Roman Caldwell",
    year: "'28",
    title: "Steel Gaze",
    avatar: "https://i.pravatar.cc/150?img=62",
    change: 0,
    score: 63,
  },
  {
    rank: 18,
    name: "Jasper Thorne",
    year: "'29",
    title: "The Wildcard",
    avatar: "https://i.pravatar.cc/150?img=3",
    change: 3,
    score: 61,
  },
  {
    rank: 19,
    name: "Milo Scott",
    year: "'27",
    title: "Baby Face Titan",
    avatar: "https://i.pravatar.cc/150?img=7",
    change: -4,
    score: 59,
  },
  {
    rank: 20,
    name: "Kieran Frost",
    year: "'26",
    title: "The Last Stand",
    avatar: "https://i.pravatar.cc/150?img=8",
    change: 2,
    score: 57,
  },
]
